baseURL = "http://dppo.cn/"
languageCode = "en-us"
title = "Dppo的个人博客"

theme = "banana"
publishDir = "docs"

[params]
  author = "Dppo"
  case = "2021"

[[menu.main]]
  name = "Home"
  weight = 10
  pageref = "/"
[[menu.main]]
  name = "Article"
  weight = 20
  pageref = "/categories/"
[[menu.main]]
  name = "Github"
  weight = 30
  pageref = "https://github.com/dppo"
[[menu.main]]
  name = "About"
  weight = 40
  pageref = "/about"