baseURL = "https://dppo.cn/"
languageCode = "en-us"
title = "Dppo的个人博客"

theme = "banana"
publishDir = "docs"

[params]
  author = "Dppo"
  bio = "高昇"
  case = "2021"
  [[params.icons]]
    name = "Github"
    icon = "/assets/github.png"
    url = "https://github.com/dppo"
  [[params.icons]]
    name = "Email"
    icon = "/assets/email.png"
    url = "mailto:xiaogao233@163.com"
  [[params.icons]]
    name = "ZhiHu"
    icon = "/assets/zhihu.png"
    url = "https://www.zhihu.com/people/dppo.cn"
  [[params.icons]]
    name = "Twitter"
    icon = "/assets/twitter.png"
    url = "https://twitter.com/xiaogao233"

[menu]
  [[menu.main]]
    name = "主页"
    weight = 10
    url = "/"
  [[menu.main]]
    name = "文章"
    weight = 20
    url = "/categories"
  [[menu.main]]
    name = "关于"
    weight = 30
    url = "/about"